menu title mo-62a MicroSD (extlinux.conf)

timeout 30

default microSD

# 40-pin GPIO mode (default): all expansion pins as plain GPIO
label microSD
  append console=ttyS2,115200n8 earlycon=ns16550a,mmio32,0x02800000 root=/dev/mmcblk1p2 rw rootfstype=ext4 rootwait
  kernel /Image
  fdt    /ti/k3-am62a7-mo-62a.dtb
  # initrd /initrd.img

# 40-pin peripheral mode: enable WKUP_I2C0 / UART5 / SPI0 / EHRPWM0 / MCASP2
label microSD-periph
  append console=ttyS2,115200n8 earlycon=ns16550a,mmio32,0x02800000 root=/dev/mmcblk1p2 rw rootfstype=ext4 rootwait
  kernel /Image
  fdt    /ti/k3-am62a7-mo-62a.dtb
  fdtoverlays /ti/k3-am62a7-mo-62a-exp-periph.dtbo
  # initrd /initrd.img
