postprocess: {}
preprocess:
  add_flip_image: false
  crop: 224
  data_layout: NCHW
  pad_color: 0
  resize: 256
  resize_with_pad: false
  reverse_channels: true
session:
  artifacts_folder: artifacts
  input_data_layout: NCHW
  input_details:
  - name: input.1Net_IN
    shape:
    - 1
    - 3
    - 224
    - 224
    type: tensor(uint8)
  input_mean: null
  input_optimization: true
  input_scale: null
  model_folder: model
  model_path: model/regnetx-200mf.onnx
  output_details:
  - name: '410'
    shape:
    - 1
    - 1000
    type: tensor(float)
  run_dir: cl-6360_onnxrt_imagenet1k_fbr-pycls_regnetx-200mf_onnx
  session_name: onnxrt
  target_device: AM62A
task_type: classification
