task_type: classification
dataset_category: imagenet
calibration_dataset:
  num_frames: 24
  name: imagenet
  num_classes: 1000
  path: ./dependencies/datasets/imagenet/val
  split: ./dependencies/datasets/imagenet/val.txt
  shuffle: true
  dataset_info: /home/tensorlab-test/projects/edgeai-algo/code/edgeai-benchmark/work_dirs/20250722-100448_develop__MINIMALSET_DEFAULTSPEED_PC/modelartifacts/AM62A/8bits/cl-0000_tflitert_imagenet1k_mlperf_mobilenet_v1_1.0_224_tflite/dataset.yaml
input_dataset:
  num_frames: 1000
  name: imagenet
  num_classes: 1000
  path: ./dependencies/datasets/imagenet/val
  split: ./dependencies/datasets/imagenet/val.txt
  shuffle: true
  dataset_info: /home/tensorlab-test/projects/edgeai-algo/code/edgeai-benchmark/work_dirs/20250722-100448_develop__MINIMALSET_DEFAULTSPEED_PC/modelartifacts/AM62A/8bits/cl-0000_tflitert_imagenet1k_mlperf_mobilenet_v1_1.0_224_tflite/dataset.yaml
postprocess: {}
preprocess:
  resize: 256
  crop: 224
  data_layout: NHWC
  reverse_channels: false
  backend: pil
  interpolation: null
  add_flip_image: false
  resize_with_pad: false
  pad_color: 0
session:
  session_name: tflitert
  work_dir: /home/tensorlab-test/projects/edgeai-algo/code/edgeai-benchmark/work_dirs/20250722-100448_develop__MINIMALSET_DEFAULTSPEED_PC/modelartifacts/AM62A/8bits
  target_machine: pc
  target_device: AM62A
  run_suffix: null
  tidl_offload: true
  input_optimization: true
  input_data_layout: NHWC
  input_mean: null
  input_scale: null
  run_dir_tree_depth: 3
  c7x_codegen: false
  runtime_options:
    platform: J7
    version: '11.1'
    tidl_tools_path: /home/tensorlab-test/projects/edgeai-algo/code/edgeai-benchmark/tools/tidl_tools_package/AM62A/tidl_tools
    artifacts_folder: /home/tensorlab-test/projects/edgeai-algo/code/edgeai-benchmark/work_dirs/20250722-100448_develop__MINIMALSET_DEFAULTSPEED_PC/modelartifacts/AM62A/8bits/cl-0000_tflitert_imagenet1k_mlperf_mobilenet_v1_1.0_224_tflite/artifacts
    tensor_bits: 8
    import: 'yes'
    advanced_options:quantization_scale_type: 4
    accuracy_level: 1
    debug_level: 0
    inference_mode: 0
    advanced_options:high_resolution_optimization: 0
    advanced_options:pre_batchnorm_fold: 1
    advanced_options:calibration_frames: 12
    advanced_options:calibration_iterations: 12
    advanced_options:activation_clipping: 1
    advanced_options:weight_clipping: 1
    advanced_options:bias_calibration: 1
    advanced_options:output_feature_16bit_names_list: ''
    advanced_options:params_16bit_names_list: ''
    advanced_options:add_data_convert_ops: 3
    ti_internal_nc_flag: 83886080
    advanced_options:quant_params_proto_path: /home/tensorlab-test/projects/edgeai-algo/code/edgeai-benchmark/work_dirs/20250722-100448_develop__MINIMALSET_DEFAULTSPEED_PC/modelartifacts/AM62A/8bits/cl-0000_tflitert_imagenet1k_mlperf_mobilenet_v1_1.0_224_tflite/model/mobilenet_v1_1.0_224_qparams.prototxt
  model_path: /home/tensorlab-test/projects/edgeai-algo/code/edgeai-modelzoo/models/vision/classification/imagenet1k/mlperf/mobilenet_v1_1.0_224.tflite
  tidl_tools_path: /home/tensorlab-test/projects/edgeai-algo/code/edgeai-benchmark/tools/tidl_tools_package/AM62A/tidl_tools
  run_dir: /home/tensorlab-test/projects/edgeai-algo/code/edgeai-benchmark/work_dirs/20250722-100448_develop__MINIMALSET_DEFAULTSPEED_PC/modelartifacts/AM62A/8bits/cl-0000_tflitert_imagenet1k_mlperf_mobilenet_v1_1.0_224_tflite
  num_tidl_subgraphs: 16
  model_id: cl-0000
  model_type: null
  input_details:
  - name: input
    shape:
    - 1
    - 224
    - 224
    - 3
    type: <class 'numpy.uint8'>
    index: 88
  output_details:
  - name: MobilenetV1/Predictions/Reshape_1
    shape:
    - 1
    - 1001
    type: <class 'numpy.float32'>
    index: 87
  num_inputs: 1
  extra_inputs: null
  tensor_bits: 8
  quant_params_proto_path: true
  supported_machines: null
  with_onnxsim: false
  shape_inference: true
  tidl_onnx_model_optimizer: false
  deny_list_from_start_end_node: null
  output_feature_16bit_names_list_from_start_end: null
  artifacts_folder: /home/tensorlab-test/projects/edgeai-algo/code/edgeai-benchmark/work_dirs/20250722-100448_develop__MINIMALSET_DEFAULTSPEED_PC/modelartifacts/AM62A/8bits/cl-0000_tflitert_imagenet1k_mlperf_mobilenet_v1_1.0_224_tflite/artifacts
  model_folder: /home/tensorlab-test/projects/edgeai-algo/code/edgeai-benchmark/work_dirs/20250722-100448_develop__MINIMALSET_DEFAULTSPEED_PC/modelartifacts/AM62A/8bits/cl-0000_tflitert_imagenet1k_mlperf_mobilenet_v1_1.0_224_tflite/model
  model_file: /home/tensorlab-test/projects/edgeai-algo/code/edgeai-benchmark/work_dirs/20250722-100448_develop__MINIMALSET_DEFAULTSPEED_PC/modelartifacts/AM62A/8bits/cl-0000_tflitert_imagenet1k_mlperf_mobilenet_v1_1.0_224_tflite/model/mobilenet_v1_1.0_224.tflite
metric:
  label_offset_pred: -1
model_info:
  metric_reference:
    accuracy_top1%: 71.676
  model_shortlist: 10
  compact_name: mobileNetV1-mlperf
  shortlisted: true
  recommended: true
