# 全局常量
DISCOVER_PORT = 47622
DISCOVER_MAGIC = b"MO62A_DISCOVER"
DISCOVER_TIMEOUT = 3.0      # 等待响应秒数
DISCOVER_RETRIES = 3

DEFAULT_SSH_USER = "debian"
DEFAULT_SSH_PORT = 22
DEFAULT_PASSWORD = "temppwd"

SERIAL_BAUD = 115200

REPORT_DIR = "reports"
