postprocess: {}
preprocess:
  add_flip_image: false
  crop:
  - 432
  - 768
  data_layout: NCHW
  pad_color: 0
  resize:
  - 432
  - 768
  resize_with_pad: false
  reverse_channels: false
session:
  artifacts_folder: artifacts
  input_data_layout: NCHW
  input_details:
  - name: x.1
    shape:
    - 1
    - 3
    - 432
    - 768
    type: tensor(float)
  input_mean:
  - 128.0
  - 128.0
  - 128.0
  input_optimization: false
  input_scale:
  - 0.015625
  - 0.015625
  - 0.015625
  model_folder: model
  model_path: model/deeplabv3plus_mnetv2_edgeailite_robokit_768x432_qat-p2.onnx
  output_details:
  - name: '1048'
    shape:
    - 1
    - 1
    - 432
    - 768
    type: tensor(int64)
  run_dir: ss-7618_onnxrt_ti-robokit_edgeai-tv_deeplabv3plus_mnetv2_edgeailite_robokit_768x432_qat-p2_onnx
  session_name: onnxrt
  target_device: AM62A
task_type: segmentation
