/* SPDX-License-Identifier: BSD-3-Clause */
/*
 * Help Library Header File for K3CONF
 *
 * Copyright (C) 2019 Texas Instruments Incorporated - https://www.ti.com/
 *	Lokesh Vutla <lokeshvutla@ti.com>
 */

#ifndef __K3CONF_HELP
#define __K3CONF_HELP

typedef enum {
	HELP_USAGE,
	HELP_SHOW,
	HELP_SHOW_HOST,
	HELP_SHOW_SEC_PROXY,
	HELP_SHOW_DEVICE,
	HELP_SHOW_CLOCK,
	HELP_SHOW_PROCESSOR,
	HELP_SHOW_MSMC,
	HELP_SHOW_RM,
	HELP_DUMP,
	HELP_DUMP_DEVICE,
	HELP_DUMP_CLOCK,
	HELP_DUMP_CLOCK_PARENT,
	HELP_DUMP_PROCESSOR,
	HELP_DUMP_RM,
	HELP_ENABLE,
	HELP_ENABLE_DEVICE,
	HELP_ENABLE_CLOCK,
	HELP_DISABLE,
	HELP_DISABLE_DEVICE,
	HELP_DISABLE_CLOCK,
	HELP_SET,
	HELP_SET_CLOCK,
	HELP_SET_CLOCK_PARENT,
	HELP_READ,
	HELP_WRITE,
	HELP_DUMP_DDRBW,
	HELP_ALL,
	HELP_CATEGORY_MAX,
} help_category;

void help(help_category cat);
#endif
